# Generated by Django 3.1.1 on 2024-01-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('published_date', models.DateTimeField()),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
